/*
Jamf Pro API

## Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

API version: production
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"reflect"
	"os"
)


type SsoSettingsAPI interface {

	/*
	V3SsoDependenciesGet Retrieve the list of Enrollment Customizations using SSO 

	Retrieves the list of Enrollment Customizations using SSO

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SsoSettingsAPIV3SsoDependenciesGetRequest
	*/
	V3SsoDependenciesGet(ctx context.Context) SsoSettingsAPIV3SsoDependenciesGetRequest

	// V3SsoDependenciesGetExecute executes the request
	//  @return EnrollmentCustomizationDependencies
	V3SsoDependenciesGetExecute(r SsoSettingsAPIV3SsoDependenciesGetRequest) (*EnrollmentCustomizationDependencies, *http.Response, error)

	/*
	V3SsoDisablePost Disable SSO 

	Disable SSO

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SsoSettingsAPIV3SsoDisablePostRequest
	*/
	V3SsoDisablePost(ctx context.Context) SsoSettingsAPIV3SsoDisablePostRequest

	// V3SsoDisablePostExecute executes the request
	V3SsoDisablePostExecute(r SsoSettingsAPIV3SsoDisablePostRequest) (*http.Response, error)

	/*
	V3SsoGet Retrieve the current Single Sign On configuration settings 

	Retrieves the current Single Sign On configuration settings

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SsoSettingsAPIV3SsoGetRequest
	*/
	V3SsoGet(ctx context.Context) SsoSettingsAPIV3SsoGetRequest

	// V3SsoGetExecute executes the request
	//  @return SsoSettingsV3
	V3SsoGetExecute(r SsoSettingsAPIV3SsoGetRequest) (*SsoSettingsV3, *http.Response, error)

	/*
	V3SsoHistoryGet Get SSO history object 

	Gets SSO history object


	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SsoSettingsAPIV3SsoHistoryGetRequest
	*/
	V3SsoHistoryGet(ctx context.Context) SsoSettingsAPIV3SsoHistoryGetRequest

	// V3SsoHistoryGetExecute executes the request
	//  @return HistorySearchResults
	V3SsoHistoryGetExecute(r SsoSettingsAPIV3SsoHistoryGetRequest) (*HistorySearchResults, *http.Response, error)

	/*
	V3SsoHistoryPost Add SSO history object notes 

	Adds SSO history object notes

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SsoSettingsAPIV3SsoHistoryPostRequest
	*/
	V3SsoHistoryPost(ctx context.Context) SsoSettingsAPIV3SsoHistoryPostRequest

	// V3SsoHistoryPostExecute executes the request
	//  @return HrefResponse
	V3SsoHistoryPostExecute(r SsoSettingsAPIV3SsoHistoryPostRequest) (*HrefResponse, *http.Response, error)

	/*
	V3SsoMetadataDownloadGet Download the Jamf Pro SAML metadata file 

	Download the Jamf Pro SAML metadata file

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SsoSettingsAPIV3SsoMetadataDownloadGetRequest
	*/
	V3SsoMetadataDownloadGet(ctx context.Context) SsoSettingsAPIV3SsoMetadataDownloadGetRequest

	// V3SsoMetadataDownloadGetExecute executes the request
	//  @return *os.File
	V3SsoMetadataDownloadGetExecute(r SsoSettingsAPIV3SsoMetadataDownloadGetRequest) (*os.File, *http.Response, error)

	/*
	V3SsoPut Updates the current Single Sign On configuration settings 

	Updates the current Single Sign On configuration settings

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return SsoSettingsAPIV3SsoPutRequest
	*/
	V3SsoPut(ctx context.Context) SsoSettingsAPIV3SsoPutRequest

	// V3SsoPutExecute executes the request
	//  @return SsoSettingsV3
	V3SsoPutExecute(r SsoSettingsAPIV3SsoPutRequest) (*SsoSettingsV3, *http.Response, error)
}

// SsoSettingsAPIService SsoSettingsAPI service
type SsoSettingsAPIService service

type SsoSettingsAPIV3SsoDependenciesGetRequest struct {
	ctx context.Context
	ApiService SsoSettingsAPI
}

func (r SsoSettingsAPIV3SsoDependenciesGetRequest) Execute() (*EnrollmentCustomizationDependencies, *http.Response, error) {
	return r.ApiService.V3SsoDependenciesGetExecute(r)
}

/*
V3SsoDependenciesGet Retrieve the list of Enrollment Customizations using SSO 

Retrieves the list of Enrollment Customizations using SSO

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SsoSettingsAPIV3SsoDependenciesGetRequest
*/
func (a *SsoSettingsAPIService) V3SsoDependenciesGet(ctx context.Context) SsoSettingsAPIV3SsoDependenciesGetRequest {
	return SsoSettingsAPIV3SsoDependenciesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return EnrollmentCustomizationDependencies
func (a *SsoSettingsAPIService) V3SsoDependenciesGetExecute(r SsoSettingsAPIV3SsoDependenciesGetRequest) (*EnrollmentCustomizationDependencies, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *EnrollmentCustomizationDependencies
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SsoSettingsAPIService.V3SsoDependenciesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3/sso/dependencies"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SsoSettingsAPIV3SsoDisablePostRequest struct {
	ctx context.Context
	ApiService SsoSettingsAPI
}

func (r SsoSettingsAPIV3SsoDisablePostRequest) Execute() (*http.Response, error) {
	return r.ApiService.V3SsoDisablePostExecute(r)
}

/*
V3SsoDisablePost Disable SSO 

Disable SSO

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SsoSettingsAPIV3SsoDisablePostRequest
*/
func (a *SsoSettingsAPIService) V3SsoDisablePost(ctx context.Context) SsoSettingsAPIV3SsoDisablePostRequest {
	return SsoSettingsAPIV3SsoDisablePostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *SsoSettingsAPIService) V3SsoDisablePostExecute(r SsoSettingsAPIV3SsoDisablePostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SsoSettingsAPIService.V3SsoDisablePost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3/sso/disable"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type SsoSettingsAPIV3SsoGetRequest struct {
	ctx context.Context
	ApiService SsoSettingsAPI
}

func (r SsoSettingsAPIV3SsoGetRequest) Execute() (*SsoSettingsV3, *http.Response, error) {
	return r.ApiService.V3SsoGetExecute(r)
}

/*
V3SsoGet Retrieve the current Single Sign On configuration settings 

Retrieves the current Single Sign On configuration settings

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SsoSettingsAPIV3SsoGetRequest
*/
func (a *SsoSettingsAPIService) V3SsoGet(ctx context.Context) SsoSettingsAPIV3SsoGetRequest {
	return SsoSettingsAPIV3SsoGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SsoSettingsV3
func (a *SsoSettingsAPIService) V3SsoGetExecute(r SsoSettingsAPIV3SsoGetRequest) (*SsoSettingsV3, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SsoSettingsV3
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SsoSettingsAPIService.V3SsoGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3/sso"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SsoSettingsAPIV3SsoHistoryGetRequest struct {
	ctx context.Context
	ApiService SsoSettingsAPI
	page *int64
	pageSize *int64
	sort *[]string
	filter *string
}

func (r SsoSettingsAPIV3SsoHistoryGetRequest) Page(page int64) SsoSettingsAPIV3SsoHistoryGetRequest {
	r.page = &page
	return r
}

func (r SsoSettingsAPIV3SsoHistoryGetRequest) PageSize(pageSize int64) SsoSettingsAPIV3SsoHistoryGetRequest {
	r.pageSize = &pageSize
	return r
}

// Sorting criteria in the format: property:asc/desc. Default sort is date:desc. Multiple sort criteria are supported and must be separated with a comma. Example: sort&#x3D;date:desc,name:asc 
func (r SsoSettingsAPIV3SsoHistoryGetRequest) Sort(sort []string) SsoSettingsAPIV3SsoHistoryGetRequest {
	r.sort = &sort
	return r
}

// Query in the RSQL format, allowing to filter history notes collection. Default filter is empty query - returning all results for the requested page. Fields allowed in the query: username, date, note, details. This param can be combined with paging and sorting. Example: filter&#x3D;username!&#x3D;admin and details&#x3D;&#x3D;*disabled* and date&lt;2019-12-15
func (r SsoSettingsAPIV3SsoHistoryGetRequest) Filter(filter string) SsoSettingsAPIV3SsoHistoryGetRequest {
	r.filter = &filter
	return r
}

func (r SsoSettingsAPIV3SsoHistoryGetRequest) Execute() (*HistorySearchResults, *http.Response, error) {
	return r.ApiService.V3SsoHistoryGetExecute(r)
}

/*
V3SsoHistoryGet Get SSO history object 

Gets SSO history object


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SsoSettingsAPIV3SsoHistoryGetRequest
*/
func (a *SsoSettingsAPIService) V3SsoHistoryGet(ctx context.Context) SsoSettingsAPIV3SsoHistoryGetRequest {
	return SsoSettingsAPIV3SsoHistoryGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return HistorySearchResults
func (a *SsoSettingsAPIService) V3SsoHistoryGetExecute(r SsoSettingsAPIV3SsoHistoryGetRequest) (*HistorySearchResults, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *HistorySearchResults
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SsoSettingsAPIService.V3SsoHistoryGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3/sso/history"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	} else {
		var defaultValue int64 = 0
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", defaultValue, "form", "")
		r.page = &defaultValue
	}
	if r.pageSize != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page-size", r.pageSize, "form", "")
	} else {
		var defaultValue int64 = 100
		parameterAddToHeaderOrQuery(localVarQueryParams, "page-size", defaultValue, "form", "")
		r.pageSize = &defaultValue
	}
	if r.sort != nil {
		t := *r.sort
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "sort", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "sort", t, "form", "multi")
		}
	} else {
		var defaultValue []string = []string{"id:desc"}
		parameterAddToHeaderOrQuery(localVarQueryParams, "sort", defaultValue, "form", "multi")
		r.sort = &defaultValue
	}
	if r.filter != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter", r.filter, "form", "")
	} else {
		var defaultValue string = ""
		parameterAddToHeaderOrQuery(localVarQueryParams, "filter", defaultValue, "form", "")
		r.filter = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SsoSettingsAPIV3SsoHistoryPostRequest struct {
	ctx context.Context
	ApiService SsoSettingsAPI
	objectHistoryNote *ObjectHistoryNote
}

// history notes to create
func (r SsoSettingsAPIV3SsoHistoryPostRequest) ObjectHistoryNote(objectHistoryNote ObjectHistoryNote) SsoSettingsAPIV3SsoHistoryPostRequest {
	r.objectHistoryNote = &objectHistoryNote
	return r
}

func (r SsoSettingsAPIV3SsoHistoryPostRequest) Execute() (*HrefResponse, *http.Response, error) {
	return r.ApiService.V3SsoHistoryPostExecute(r)
}

/*
V3SsoHistoryPost Add SSO history object notes 

Adds SSO history object notes

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SsoSettingsAPIV3SsoHistoryPostRequest
*/
func (a *SsoSettingsAPIService) V3SsoHistoryPost(ctx context.Context) SsoSettingsAPIV3SsoHistoryPostRequest {
	return SsoSettingsAPIV3SsoHistoryPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return HrefResponse
func (a *SsoSettingsAPIService) V3SsoHistoryPostExecute(r SsoSettingsAPIV3SsoHistoryPostRequest) (*HrefResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *HrefResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SsoSettingsAPIService.V3SsoHistoryPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3/sso/history"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.objectHistoryNote == nil {
		return localVarReturnValue, nil, reportError("objectHistoryNote is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.objectHistoryNote
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 503 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SsoSettingsAPIV3SsoMetadataDownloadGetRequest struct {
	ctx context.Context
	ApiService SsoSettingsAPI
}

func (r SsoSettingsAPIV3SsoMetadataDownloadGetRequest) Execute() (*os.File, *http.Response, error) {
	return r.ApiService.V3SsoMetadataDownloadGetExecute(r)
}

/*
V3SsoMetadataDownloadGet Download the Jamf Pro SAML metadata file 

Download the Jamf Pro SAML metadata file

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SsoSettingsAPIV3SsoMetadataDownloadGetRequest
*/
func (a *SsoSettingsAPIService) V3SsoMetadataDownloadGet(ctx context.Context) SsoSettingsAPIV3SsoMetadataDownloadGetRequest {
	return SsoSettingsAPIV3SsoMetadataDownloadGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return *os.File
func (a *SsoSettingsAPIService) V3SsoMetadataDownloadGetExecute(r SsoSettingsAPIV3SsoMetadataDownloadGetRequest) (*os.File, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *os.File
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SsoSettingsAPIService.V3SsoMetadataDownloadGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3/sso/metadata/download"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"text/plain"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type SsoSettingsAPIV3SsoPutRequest struct {
	ctx context.Context
	ApiService SsoSettingsAPI
	ssoSettingsV3 *SsoSettingsV3
}

func (r SsoSettingsAPIV3SsoPutRequest) SsoSettingsV3(ssoSettingsV3 SsoSettingsV3) SsoSettingsAPIV3SsoPutRequest {
	r.ssoSettingsV3 = &ssoSettingsV3
	return r
}

func (r SsoSettingsAPIV3SsoPutRequest) Execute() (*SsoSettingsV3, *http.Response, error) {
	return r.ApiService.V3SsoPutExecute(r)
}

/*
V3SsoPut Updates the current Single Sign On configuration settings 

Updates the current Single Sign On configuration settings

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return SsoSettingsAPIV3SsoPutRequest
*/
func (a *SsoSettingsAPIService) V3SsoPut(ctx context.Context) SsoSettingsAPIV3SsoPutRequest {
	return SsoSettingsAPIV3SsoPutRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return SsoSettingsV3
func (a *SsoSettingsAPIService) V3SsoPutExecute(r SsoSettingsAPIV3SsoPutRequest) (*SsoSettingsV3, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPut
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *SsoSettingsV3
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SsoSettingsAPIService.V3SsoPut")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v3/sso"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.ssoSettingsV3
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v ApiError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
