/*
Jamf Pro API

## Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

API version: production
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ClientCheckInV3 struct for ClientCheckInV3
type ClientCheckInV3 struct {
	// Suggested values are 5, 15, 30, or 60. Web interface will not display correctly if not one of those. Minimim is 5, maximum is 60.
	CheckInFrequency *int32 `json:"checkInFrequency,omitempty"`
	CreateHooks *bool `json:"createHooks,omitempty"`
	HookLog *bool `json:"hookLog,omitempty"`
	HookPolicies *bool `json:"hookPolicies,omitempty"`
	CreateStartupScript *bool `json:"createStartupScript,omitempty"`
	StartupLog *bool `json:"startupLog,omitempty"`
	StartupPolicies *bool `json:"startupPolicies,omitempty"`
	StartupSsh *bool `json:"startupSsh,omitempty"`
	EnableLocalConfigurationProfiles *bool `json:"enableLocalConfigurationProfiles,omitempty"`
}

// NewClientCheckInV3 instantiates a new ClientCheckInV3 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientCheckInV3() *ClientCheckInV3 {
	this := ClientCheckInV3{}
	var checkInFrequency int32 = 15
	this.CheckInFrequency = &checkInFrequency
	var createHooks bool = false
	this.CreateHooks = &createHooks
	var hookLog bool = false
	this.HookLog = &hookLog
	var hookPolicies bool = false
	this.HookPolicies = &hookPolicies
	var createStartupScript bool = false
	this.CreateStartupScript = &createStartupScript
	var startupLog bool = false
	this.StartupLog = &startupLog
	var startupPolicies bool = false
	this.StartupPolicies = &startupPolicies
	var startupSsh bool = false
	this.StartupSsh = &startupSsh
	var enableLocalConfigurationProfiles bool = false
	this.EnableLocalConfigurationProfiles = &enableLocalConfigurationProfiles
	return &this
}

// NewClientCheckInV3WithDefaults instantiates a new ClientCheckInV3 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientCheckInV3WithDefaults() *ClientCheckInV3 {
	this := ClientCheckInV3{}
	var checkInFrequency int32 = 15
	this.CheckInFrequency = &checkInFrequency
	var createHooks bool = false
	this.CreateHooks = &createHooks
	var hookLog bool = false
	this.HookLog = &hookLog
	var hookPolicies bool = false
	this.HookPolicies = &hookPolicies
	var createStartupScript bool = false
	this.CreateStartupScript = &createStartupScript
	var startupLog bool = false
	this.StartupLog = &startupLog
	var startupPolicies bool = false
	this.StartupPolicies = &startupPolicies
	var startupSsh bool = false
	this.StartupSsh = &startupSsh
	var enableLocalConfigurationProfiles bool = false
	this.EnableLocalConfigurationProfiles = &enableLocalConfigurationProfiles
	return &this
}

// GetCheckInFrequency returns the CheckInFrequency field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetCheckInFrequency() int32 {
	if o == nil || o.CheckInFrequency == nil {
		var ret int32
		return ret
	}
	return *o.CheckInFrequency
}

// GetCheckInFrequencyOk returns a tuple with the CheckInFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetCheckInFrequencyOk() (*int32, bool) {
	if o == nil || o.CheckInFrequency == nil {
		return nil, false
	}
	return o.CheckInFrequency, true
}

// HasCheckInFrequency returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasCheckInFrequency() bool {
	if o != nil && o.CheckInFrequency != nil {
		return true
	}

	return false
}

// SetCheckInFrequency gets a reference to the given int32 and assigns it to the CheckInFrequency field.
func (o *ClientCheckInV3) SetCheckInFrequency(v int32) {
	o.CheckInFrequency = &v
}

// GetCreateHooks returns the CreateHooks field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetCreateHooks() bool {
	if o == nil || o.CreateHooks == nil {
		var ret bool
		return ret
	}
	return *o.CreateHooks
}

// GetCreateHooksOk returns a tuple with the CreateHooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetCreateHooksOk() (*bool, bool) {
	if o == nil || o.CreateHooks == nil {
		return nil, false
	}
	return o.CreateHooks, true
}

// HasCreateHooks returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasCreateHooks() bool {
	if o != nil && o.CreateHooks != nil {
		return true
	}

	return false
}

// SetCreateHooks gets a reference to the given bool and assigns it to the CreateHooks field.
func (o *ClientCheckInV3) SetCreateHooks(v bool) {
	o.CreateHooks = &v
}

// GetHookLog returns the HookLog field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetHookLog() bool {
	if o == nil || o.HookLog == nil {
		var ret bool
		return ret
	}
	return *o.HookLog
}

// GetHookLogOk returns a tuple with the HookLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetHookLogOk() (*bool, bool) {
	if o == nil || o.HookLog == nil {
		return nil, false
	}
	return o.HookLog, true
}

// HasHookLog returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasHookLog() bool {
	if o != nil && o.HookLog != nil {
		return true
	}

	return false
}

// SetHookLog gets a reference to the given bool and assigns it to the HookLog field.
func (o *ClientCheckInV3) SetHookLog(v bool) {
	o.HookLog = &v
}

// GetHookPolicies returns the HookPolicies field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetHookPolicies() bool {
	if o == nil || o.HookPolicies == nil {
		var ret bool
		return ret
	}
	return *o.HookPolicies
}

// GetHookPoliciesOk returns a tuple with the HookPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetHookPoliciesOk() (*bool, bool) {
	if o == nil || o.HookPolicies == nil {
		return nil, false
	}
	return o.HookPolicies, true
}

// HasHookPolicies returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasHookPolicies() bool {
	if o != nil && o.HookPolicies != nil {
		return true
	}

	return false
}

// SetHookPolicies gets a reference to the given bool and assigns it to the HookPolicies field.
func (o *ClientCheckInV3) SetHookPolicies(v bool) {
	o.HookPolicies = &v
}

// GetCreateStartupScript returns the CreateStartupScript field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetCreateStartupScript() bool {
	if o == nil || o.CreateStartupScript == nil {
		var ret bool
		return ret
	}
	return *o.CreateStartupScript
}

// GetCreateStartupScriptOk returns a tuple with the CreateStartupScript field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetCreateStartupScriptOk() (*bool, bool) {
	if o == nil || o.CreateStartupScript == nil {
		return nil, false
	}
	return o.CreateStartupScript, true
}

// HasCreateStartupScript returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasCreateStartupScript() bool {
	if o != nil && o.CreateStartupScript != nil {
		return true
	}

	return false
}

// SetCreateStartupScript gets a reference to the given bool and assigns it to the CreateStartupScript field.
func (o *ClientCheckInV3) SetCreateStartupScript(v bool) {
	o.CreateStartupScript = &v
}

// GetStartupLog returns the StartupLog field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetStartupLog() bool {
	if o == nil || o.StartupLog == nil {
		var ret bool
		return ret
	}
	return *o.StartupLog
}

// GetStartupLogOk returns a tuple with the StartupLog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetStartupLogOk() (*bool, bool) {
	if o == nil || o.StartupLog == nil {
		return nil, false
	}
	return o.StartupLog, true
}

// HasStartupLog returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasStartupLog() bool {
	if o != nil && o.StartupLog != nil {
		return true
	}

	return false
}

// SetStartupLog gets a reference to the given bool and assigns it to the StartupLog field.
func (o *ClientCheckInV3) SetStartupLog(v bool) {
	o.StartupLog = &v
}

// GetStartupPolicies returns the StartupPolicies field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetStartupPolicies() bool {
	if o == nil || o.StartupPolicies == nil {
		var ret bool
		return ret
	}
	return *o.StartupPolicies
}

// GetStartupPoliciesOk returns a tuple with the StartupPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetStartupPoliciesOk() (*bool, bool) {
	if o == nil || o.StartupPolicies == nil {
		return nil, false
	}
	return o.StartupPolicies, true
}

// HasStartupPolicies returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasStartupPolicies() bool {
	if o != nil && o.StartupPolicies != nil {
		return true
	}

	return false
}

// SetStartupPolicies gets a reference to the given bool and assigns it to the StartupPolicies field.
func (o *ClientCheckInV3) SetStartupPolicies(v bool) {
	o.StartupPolicies = &v
}

// GetStartupSsh returns the StartupSsh field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetStartupSsh() bool {
	if o == nil || o.StartupSsh == nil {
		var ret bool
		return ret
	}
	return *o.StartupSsh
}

// GetStartupSshOk returns a tuple with the StartupSsh field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetStartupSshOk() (*bool, bool) {
	if o == nil || o.StartupSsh == nil {
		return nil, false
	}
	return o.StartupSsh, true
}

// HasStartupSsh returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasStartupSsh() bool {
	if o != nil && o.StartupSsh != nil {
		return true
	}

	return false
}

// SetStartupSsh gets a reference to the given bool and assigns it to the StartupSsh field.
func (o *ClientCheckInV3) SetStartupSsh(v bool) {
	o.StartupSsh = &v
}

// GetEnableLocalConfigurationProfiles returns the EnableLocalConfigurationProfiles field value if set, zero value otherwise.
func (o *ClientCheckInV3) GetEnableLocalConfigurationProfiles() bool {
	if o == nil || o.EnableLocalConfigurationProfiles == nil {
		var ret bool
		return ret
	}
	return *o.EnableLocalConfigurationProfiles
}

// GetEnableLocalConfigurationProfilesOk returns a tuple with the EnableLocalConfigurationProfiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientCheckInV3) GetEnableLocalConfigurationProfilesOk() (*bool, bool) {
	if o == nil || o.EnableLocalConfigurationProfiles == nil {
		return nil, false
	}
	return o.EnableLocalConfigurationProfiles, true
}

// HasEnableLocalConfigurationProfiles returns a boolean if a field has been set.
func (o *ClientCheckInV3) HasEnableLocalConfigurationProfiles() bool {
	if o != nil && o.EnableLocalConfigurationProfiles != nil {
		return true
	}

	return false
}

// SetEnableLocalConfigurationProfiles gets a reference to the given bool and assigns it to the EnableLocalConfigurationProfiles field.
func (o *ClientCheckInV3) SetEnableLocalConfigurationProfiles(v bool) {
	o.EnableLocalConfigurationProfiles = &v
}

func (o ClientCheckInV3) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CheckInFrequency != nil {
		toSerialize["checkInFrequency"] = o.CheckInFrequency
	}
	if o.CreateHooks != nil {
		toSerialize["createHooks"] = o.CreateHooks
	}
	if o.HookLog != nil {
		toSerialize["hookLog"] = o.HookLog
	}
	if o.HookPolicies != nil {
		toSerialize["hookPolicies"] = o.HookPolicies
	}
	if o.CreateStartupScript != nil {
		toSerialize["createStartupScript"] = o.CreateStartupScript
	}
	if o.StartupLog != nil {
		toSerialize["startupLog"] = o.StartupLog
	}
	if o.StartupPolicies != nil {
		toSerialize["startupPolicies"] = o.StartupPolicies
	}
	if o.StartupSsh != nil {
		toSerialize["startupSsh"] = o.StartupSsh
	}
	if o.EnableLocalConfigurationProfiles != nil {
		toSerialize["enableLocalConfigurationProfiles"] = o.EnableLocalConfigurationProfiles
	}
	return json.Marshal(toSerialize)
}

type NullableClientCheckInV3 struct {
	value *ClientCheckInV3
	isSet bool
}

func (v NullableClientCheckInV3) Get() *ClientCheckInV3 {
	return v.value
}

func (v *NullableClientCheckInV3) Set(val *ClientCheckInV3) {
	v.value = val
	v.isSet = true
}

func (v NullableClientCheckInV3) IsSet() bool {
	return v.isSet
}

func (v *NullableClientCheckInV3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientCheckInV3(val *ClientCheckInV3) *NullableClientCheckInV3 {
	return &NullableClientCheckInV3{value: val, isSet: true}
}

func (v NullableClientCheckInV3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientCheckInV3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


