/*
Jamf Pro API

## Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

API version: production
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the MdmRenewalError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MdmRenewalError{}

// MdmRenewalError struct for MdmRenewalError
type MdmRenewalError struct {
	// Unique identifier for the MDM renewal error
	MdmRenewalErrorId string `json:"mdmRenewalErrorId"`
	// The client management ID associated with this error
	ClientManagementId string `json:"clientManagementId"`
	MdmRenewalErrorType MdmRenewalErrorType `json:"mdmRenewalErrorType"`
	// Timestamp when the error occurred (ISO 8601 format)
	ErrorTimeStamp *time.Time `json:"errorTimeStamp,omitempty"`
	// Number of times this error has occurred
	FailureCount *int64 `json:"failureCount,omitempty"`
}

type _MdmRenewalError MdmRenewalError

// NewMdmRenewalError instantiates a new MdmRenewalError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMdmRenewalError(mdmRenewalErrorId string, clientManagementId string, mdmRenewalErrorType MdmRenewalErrorType) *MdmRenewalError {
	this := MdmRenewalError{}
	this.MdmRenewalErrorId = mdmRenewalErrorId
	this.ClientManagementId = clientManagementId
	this.MdmRenewalErrorType = mdmRenewalErrorType
	return &this
}

// NewMdmRenewalErrorWithDefaults instantiates a new MdmRenewalError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMdmRenewalErrorWithDefaults() *MdmRenewalError {
	this := MdmRenewalError{}
	return &this
}

// GetMdmRenewalErrorId returns the MdmRenewalErrorId field value
func (o *MdmRenewalError) GetMdmRenewalErrorId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MdmRenewalErrorId
}

// GetMdmRenewalErrorIdOk returns a tuple with the MdmRenewalErrorId field value
// and a boolean to check if the value has been set.
func (o *MdmRenewalError) GetMdmRenewalErrorIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MdmRenewalErrorId, true
}

// SetMdmRenewalErrorId sets field value
func (o *MdmRenewalError) SetMdmRenewalErrorId(v string) {
	o.MdmRenewalErrorId = v
}

// GetClientManagementId returns the ClientManagementId field value
func (o *MdmRenewalError) GetClientManagementId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ClientManagementId
}

// GetClientManagementIdOk returns a tuple with the ClientManagementId field value
// and a boolean to check if the value has been set.
func (o *MdmRenewalError) GetClientManagementIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientManagementId, true
}

// SetClientManagementId sets field value
func (o *MdmRenewalError) SetClientManagementId(v string) {
	o.ClientManagementId = v
}

// GetMdmRenewalErrorType returns the MdmRenewalErrorType field value
func (o *MdmRenewalError) GetMdmRenewalErrorType() MdmRenewalErrorType {
	if o == nil {
		var ret MdmRenewalErrorType
		return ret
	}

	return o.MdmRenewalErrorType
}

// GetMdmRenewalErrorTypeOk returns a tuple with the MdmRenewalErrorType field value
// and a boolean to check if the value has been set.
func (o *MdmRenewalError) GetMdmRenewalErrorTypeOk() (*MdmRenewalErrorType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MdmRenewalErrorType, true
}

// SetMdmRenewalErrorType sets field value
func (o *MdmRenewalError) SetMdmRenewalErrorType(v MdmRenewalErrorType) {
	o.MdmRenewalErrorType = v
}

// GetErrorTimeStamp returns the ErrorTimeStamp field value if set, zero value otherwise.
func (o *MdmRenewalError) GetErrorTimeStamp() time.Time {
	if o == nil || IsNil(o.ErrorTimeStamp) {
		var ret time.Time
		return ret
	}
	return *o.ErrorTimeStamp
}

// GetErrorTimeStampOk returns a tuple with the ErrorTimeStamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmRenewalError) GetErrorTimeStampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ErrorTimeStamp) {
		return nil, false
	}
	return o.ErrorTimeStamp, true
}

// HasErrorTimeStamp returns a boolean if a field has been set.
func (o *MdmRenewalError) HasErrorTimeStamp() bool {
	if o != nil && !IsNil(o.ErrorTimeStamp) {
		return true
	}

	return false
}

// SetErrorTimeStamp gets a reference to the given time.Time and assigns it to the ErrorTimeStamp field.
func (o *MdmRenewalError) SetErrorTimeStamp(v time.Time) {
	o.ErrorTimeStamp = &v
}

// GetFailureCount returns the FailureCount field value if set, zero value otherwise.
func (o *MdmRenewalError) GetFailureCount() int64 {
	if o == nil || IsNil(o.FailureCount) {
		var ret int64
		return ret
	}
	return *o.FailureCount
}

// GetFailureCountOk returns a tuple with the FailureCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MdmRenewalError) GetFailureCountOk() (*int64, bool) {
	if o == nil || IsNil(o.FailureCount) {
		return nil, false
	}
	return o.FailureCount, true
}

// HasFailureCount returns a boolean if a field has been set.
func (o *MdmRenewalError) HasFailureCount() bool {
	if o != nil && !IsNil(o.FailureCount) {
		return true
	}

	return false
}

// SetFailureCount gets a reference to the given int64 and assigns it to the FailureCount field.
func (o *MdmRenewalError) SetFailureCount(v int64) {
	o.FailureCount = &v
}

func (o MdmRenewalError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MdmRenewalError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mdmRenewalErrorId"] = o.MdmRenewalErrorId
	toSerialize["clientManagementId"] = o.ClientManagementId
	toSerialize["mdmRenewalErrorType"] = o.MdmRenewalErrorType
	if !IsNil(o.ErrorTimeStamp) {
		toSerialize["errorTimeStamp"] = o.ErrorTimeStamp
	}
	if !IsNil(o.FailureCount) {
		toSerialize["failureCount"] = o.FailureCount
	}
	return toSerialize, nil
}

func (o *MdmRenewalError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mdmRenewalErrorId",
		"clientManagementId",
		"mdmRenewalErrorType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMdmRenewalError := _MdmRenewalError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMdmRenewalError)

	if err != nil {
		return err
	}

	*o = MdmRenewalError(varMdmRenewalError)

	return err
}

type NullableMdmRenewalError struct {
	value *MdmRenewalError
	isSet bool
}

func (v NullableMdmRenewalError) Get() *MdmRenewalError {
	return v.value
}

func (v *NullableMdmRenewalError) Set(val *MdmRenewalError) {
	v.value = val
	v.isSet = true
}

func (v NullableMdmRenewalError) IsSet() bool {
	return v.isSet
}

func (v *NullableMdmRenewalError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMdmRenewalError(val *MdmRenewalError) *NullableMdmRenewalError {
	return &NullableMdmRenewalError{value: val, isSet: true}
}

func (v NullableMdmRenewalError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMdmRenewalError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


