/*
Jamf Pro API

## Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

API version: production
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// ComputerOperatingSystem struct for ComputerOperatingSystem
type ComputerOperatingSystem struct {
	Name *string `json:"name,omitempty"`
	Version *string `json:"version,omitempty"`
	Build *string `json:"build,omitempty"`
	ActiveDirectoryStatus *string `json:"activeDirectoryStatus,omitempty"`
	FileVault2Status *string `json:"fileVault2Status,omitempty"`
	SoftwareUpdateDeviceId *string `json:"softwareUpdateDeviceId,omitempty"`
	ExtensionAttributes []ComputerExtensionAttribute `json:"extensionAttributes,omitempty"`
}

// NewComputerOperatingSystem instantiates a new ComputerOperatingSystem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComputerOperatingSystem() *ComputerOperatingSystem {
	this := ComputerOperatingSystem{}
	return &this
}

// NewComputerOperatingSystemWithDefaults instantiates a new ComputerOperatingSystem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComputerOperatingSystemWithDefaults() *ComputerOperatingSystem {
	this := ComputerOperatingSystem{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ComputerOperatingSystem) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerOperatingSystem) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ComputerOperatingSystem) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ComputerOperatingSystem) SetName(v string) {
	o.Name = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ComputerOperatingSystem) GetVersion() string {
	if o == nil || o.Version == nil {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerOperatingSystem) GetVersionOk() (*string, bool) {
	if o == nil || o.Version == nil {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ComputerOperatingSystem) HasVersion() bool {
	if o != nil && o.Version != nil {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ComputerOperatingSystem) SetVersion(v string) {
	o.Version = &v
}

// GetBuild returns the Build field value if set, zero value otherwise.
func (o *ComputerOperatingSystem) GetBuild() string {
	if o == nil || o.Build == nil {
		var ret string
		return ret
	}
	return *o.Build
}

// GetBuildOk returns a tuple with the Build field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerOperatingSystem) GetBuildOk() (*string, bool) {
	if o == nil || o.Build == nil {
		return nil, false
	}
	return o.Build, true
}

// HasBuild returns a boolean if a field has been set.
func (o *ComputerOperatingSystem) HasBuild() bool {
	if o != nil && o.Build != nil {
		return true
	}

	return false
}

// SetBuild gets a reference to the given string and assigns it to the Build field.
func (o *ComputerOperatingSystem) SetBuild(v string) {
	o.Build = &v
}

// GetActiveDirectoryStatus returns the ActiveDirectoryStatus field value if set, zero value otherwise.
func (o *ComputerOperatingSystem) GetActiveDirectoryStatus() string {
	if o == nil || o.ActiveDirectoryStatus == nil {
		var ret string
		return ret
	}
	return *o.ActiveDirectoryStatus
}

// GetActiveDirectoryStatusOk returns a tuple with the ActiveDirectoryStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerOperatingSystem) GetActiveDirectoryStatusOk() (*string, bool) {
	if o == nil || o.ActiveDirectoryStatus == nil {
		return nil, false
	}
	return o.ActiveDirectoryStatus, true
}

// HasActiveDirectoryStatus returns a boolean if a field has been set.
func (o *ComputerOperatingSystem) HasActiveDirectoryStatus() bool {
	if o != nil && o.ActiveDirectoryStatus != nil {
		return true
	}

	return false
}

// SetActiveDirectoryStatus gets a reference to the given string and assigns it to the ActiveDirectoryStatus field.
func (o *ComputerOperatingSystem) SetActiveDirectoryStatus(v string) {
	o.ActiveDirectoryStatus = &v
}

// GetFileVault2Status returns the FileVault2Status field value if set, zero value otherwise.
func (o *ComputerOperatingSystem) GetFileVault2Status() string {
	if o == nil || o.FileVault2Status == nil {
		var ret string
		return ret
	}
	return *o.FileVault2Status
}

// GetFileVault2StatusOk returns a tuple with the FileVault2Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerOperatingSystem) GetFileVault2StatusOk() (*string, bool) {
	if o == nil || o.FileVault2Status == nil {
		return nil, false
	}
	return o.FileVault2Status, true
}

// HasFileVault2Status returns a boolean if a field has been set.
func (o *ComputerOperatingSystem) HasFileVault2Status() bool {
	if o != nil && o.FileVault2Status != nil {
		return true
	}

	return false
}

// SetFileVault2Status gets a reference to the given string and assigns it to the FileVault2Status field.
func (o *ComputerOperatingSystem) SetFileVault2Status(v string) {
	o.FileVault2Status = &v
}

// GetSoftwareUpdateDeviceId returns the SoftwareUpdateDeviceId field value if set, zero value otherwise.
func (o *ComputerOperatingSystem) GetSoftwareUpdateDeviceId() string {
	if o == nil || o.SoftwareUpdateDeviceId == nil {
		var ret string
		return ret
	}
	return *o.SoftwareUpdateDeviceId
}

// GetSoftwareUpdateDeviceIdOk returns a tuple with the SoftwareUpdateDeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerOperatingSystem) GetSoftwareUpdateDeviceIdOk() (*string, bool) {
	if o == nil || o.SoftwareUpdateDeviceId == nil {
		return nil, false
	}
	return o.SoftwareUpdateDeviceId, true
}

// HasSoftwareUpdateDeviceId returns a boolean if a field has been set.
func (o *ComputerOperatingSystem) HasSoftwareUpdateDeviceId() bool {
	if o != nil && o.SoftwareUpdateDeviceId != nil {
		return true
	}

	return false
}

// SetSoftwareUpdateDeviceId gets a reference to the given string and assigns it to the SoftwareUpdateDeviceId field.
func (o *ComputerOperatingSystem) SetSoftwareUpdateDeviceId(v string) {
	o.SoftwareUpdateDeviceId = &v
}

// GetExtensionAttributes returns the ExtensionAttributes field value if set, zero value otherwise.
func (o *ComputerOperatingSystem) GetExtensionAttributes() []ComputerExtensionAttribute {
	if o == nil || o.ExtensionAttributes == nil {
		var ret []ComputerExtensionAttribute
		return ret
	}
	return o.ExtensionAttributes
}

// GetExtensionAttributesOk returns a tuple with the ExtensionAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComputerOperatingSystem) GetExtensionAttributesOk() ([]ComputerExtensionAttribute, bool) {
	if o == nil || o.ExtensionAttributes == nil {
		return nil, false
	}
	return o.ExtensionAttributes, true
}

// HasExtensionAttributes returns a boolean if a field has been set.
func (o *ComputerOperatingSystem) HasExtensionAttributes() bool {
	if o != nil && o.ExtensionAttributes != nil {
		return true
	}

	return false
}

// SetExtensionAttributes gets a reference to the given []ComputerExtensionAttribute and assigns it to the ExtensionAttributes field.
func (o *ComputerOperatingSystem) SetExtensionAttributes(v []ComputerExtensionAttribute) {
	o.ExtensionAttributes = v
}

func (o ComputerOperatingSystem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Version != nil {
		toSerialize["version"] = o.Version
	}
	if o.Build != nil {
		toSerialize["build"] = o.Build
	}
	if o.ActiveDirectoryStatus != nil {
		toSerialize["activeDirectoryStatus"] = o.ActiveDirectoryStatus
	}
	if o.FileVault2Status != nil {
		toSerialize["fileVault2Status"] = o.FileVault2Status
	}
	if o.SoftwareUpdateDeviceId != nil {
		toSerialize["softwareUpdateDeviceId"] = o.SoftwareUpdateDeviceId
	}
	if o.ExtensionAttributes != nil {
		toSerialize["extensionAttributes"] = o.ExtensionAttributes
	}
	return json.Marshal(toSerialize)
}

type NullableComputerOperatingSystem struct {
	value *ComputerOperatingSystem
	isSet bool
}

func (v NullableComputerOperatingSystem) Get() *ComputerOperatingSystem {
	return v.value
}

func (v *NullableComputerOperatingSystem) Set(val *ComputerOperatingSystem) {
	v.value = val
	v.isSet = true
}

func (v NullableComputerOperatingSystem) IsSet() bool {
	return v.isSet
}

func (v *NullableComputerOperatingSystem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComputerOperatingSystem(val *ComputerOperatingSystem) *NullableComputerOperatingSystem {
	return &NullableComputerOperatingSystem{value: val, isSet: true}
}

func (v NullableComputerOperatingSystem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComputerOperatingSystem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


