/*
Jamf Pro API

## Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

API version: production
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the SmartComputerGroupSearch type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SmartComputerGroupSearch{}

// SmartComputerGroupSearch struct for SmartComputerGroupSearch
type SmartComputerGroupSearch struct {
	Id *string `json:"id,omitempty"`
	SiteId *string `json:"siteId,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	MembershipCount *int64 `json:"membershipCount,omitempty"`
}

// NewSmartComputerGroupSearch instantiates a new SmartComputerGroupSearch object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSmartComputerGroupSearch() *SmartComputerGroupSearch {
	this := SmartComputerGroupSearch{}
	return &this
}

// NewSmartComputerGroupSearchWithDefaults instantiates a new SmartComputerGroupSearch object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSmartComputerGroupSearchWithDefaults() *SmartComputerGroupSearch {
	this := SmartComputerGroupSearch{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SmartComputerGroupSearch) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartComputerGroupSearch) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SmartComputerGroupSearch) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SmartComputerGroupSearch) SetId(v string) {
	o.Id = &v
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *SmartComputerGroupSearch) GetSiteId() string {
	if o == nil || IsNil(o.SiteId) {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartComputerGroupSearch) GetSiteIdOk() (*string, bool) {
	if o == nil || IsNil(o.SiteId) {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *SmartComputerGroupSearch) HasSiteId() bool {
	if o != nil && !IsNil(o.SiteId) {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *SmartComputerGroupSearch) SetSiteId(v string) {
	o.SiteId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SmartComputerGroupSearch) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartComputerGroupSearch) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SmartComputerGroupSearch) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SmartComputerGroupSearch) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *SmartComputerGroupSearch) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartComputerGroupSearch) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *SmartComputerGroupSearch) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *SmartComputerGroupSearch) SetDescription(v string) {
	o.Description = &v
}

// GetMembershipCount returns the MembershipCount field value if set, zero value otherwise.
func (o *SmartComputerGroupSearch) GetMembershipCount() int64 {
	if o == nil || IsNil(o.MembershipCount) {
		var ret int64
		return ret
	}
	return *o.MembershipCount
}

// GetMembershipCountOk returns a tuple with the MembershipCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SmartComputerGroupSearch) GetMembershipCountOk() (*int64, bool) {
	if o == nil || IsNil(o.MembershipCount) {
		return nil, false
	}
	return o.MembershipCount, true
}

// HasMembershipCount returns a boolean if a field has been set.
func (o *SmartComputerGroupSearch) HasMembershipCount() bool {
	if o != nil && !IsNil(o.MembershipCount) {
		return true
	}

	return false
}

// SetMembershipCount gets a reference to the given int64 and assigns it to the MembershipCount field.
func (o *SmartComputerGroupSearch) SetMembershipCount(v int64) {
	o.MembershipCount = &v
}

func (o SmartComputerGroupSearch) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SmartComputerGroupSearch) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.SiteId) {
		toSerialize["siteId"] = o.SiteId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.MembershipCount) {
		toSerialize["membershipCount"] = o.MembershipCount
	}
	return toSerialize, nil
}

type NullableSmartComputerGroupSearch struct {
	value *SmartComputerGroupSearch
	isSet bool
}

func (v NullableSmartComputerGroupSearch) Get() *SmartComputerGroupSearch {
	return v.value
}

func (v *NullableSmartComputerGroupSearch) Set(val *SmartComputerGroupSearch) {
	v.value = val
	v.isSet = true
}

func (v NullableSmartComputerGroupSearch) IsSet() bool {
	return v.isSet
}

func (v *NullableSmartComputerGroupSearch) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSmartComputerGroupSearch(val *SmartComputerGroupSearch) *NullableSmartComputerGroupSearch {
	return &NullableSmartComputerGroupSearch{value: val, isSet: true}
}

func (v NullableSmartComputerGroupSearch) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSmartComputerGroupSearch) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


