/*
Jamf Pro API

## Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

API version: production
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SharedDeviceComplianceFeatureToggle type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SharedDeviceComplianceFeatureToggle{}

// SharedDeviceComplianceFeatureToggle struct for SharedDeviceComplianceFeatureToggle
type SharedDeviceComplianceFeatureToggle struct {
	SharedDeviceFeatureEnabled bool `json:"sharedDeviceFeatureEnabled"`
}

type _SharedDeviceComplianceFeatureToggle SharedDeviceComplianceFeatureToggle

// NewSharedDeviceComplianceFeatureToggle instantiates a new SharedDeviceComplianceFeatureToggle object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSharedDeviceComplianceFeatureToggle(sharedDeviceFeatureEnabled bool) *SharedDeviceComplianceFeatureToggle {
	this := SharedDeviceComplianceFeatureToggle{}
	this.SharedDeviceFeatureEnabled = sharedDeviceFeatureEnabled
	return &this
}

// NewSharedDeviceComplianceFeatureToggleWithDefaults instantiates a new SharedDeviceComplianceFeatureToggle object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSharedDeviceComplianceFeatureToggleWithDefaults() *SharedDeviceComplianceFeatureToggle {
	this := SharedDeviceComplianceFeatureToggle{}
	return &this
}

// GetSharedDeviceFeatureEnabled returns the SharedDeviceFeatureEnabled field value
func (o *SharedDeviceComplianceFeatureToggle) GetSharedDeviceFeatureEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SharedDeviceFeatureEnabled
}

// GetSharedDeviceFeatureEnabledOk returns a tuple with the SharedDeviceFeatureEnabled field value
// and a boolean to check if the value has been set.
func (o *SharedDeviceComplianceFeatureToggle) GetSharedDeviceFeatureEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SharedDeviceFeatureEnabled, true
}

// SetSharedDeviceFeatureEnabled sets field value
func (o *SharedDeviceComplianceFeatureToggle) SetSharedDeviceFeatureEnabled(v bool) {
	o.SharedDeviceFeatureEnabled = v
}

func (o SharedDeviceComplianceFeatureToggle) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SharedDeviceComplianceFeatureToggle) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sharedDeviceFeatureEnabled"] = o.SharedDeviceFeatureEnabled
	return toSerialize, nil
}

func (o *SharedDeviceComplianceFeatureToggle) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sharedDeviceFeatureEnabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSharedDeviceComplianceFeatureToggle := _SharedDeviceComplianceFeatureToggle{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSharedDeviceComplianceFeatureToggle)

	if err != nil {
		return err
	}

	*o = SharedDeviceComplianceFeatureToggle(varSharedDeviceComplianceFeatureToggle)

	return err
}

type NullableSharedDeviceComplianceFeatureToggle struct {
	value *SharedDeviceComplianceFeatureToggle
	isSet bool
}

func (v NullableSharedDeviceComplianceFeatureToggle) Get() *SharedDeviceComplianceFeatureToggle {
	return v.value
}

func (v *NullableSharedDeviceComplianceFeatureToggle) Set(val *SharedDeviceComplianceFeatureToggle) {
	v.value = val
	v.isSet = true
}

func (v NullableSharedDeviceComplianceFeatureToggle) IsSet() bool {
	return v.isSet
}

func (v *NullableSharedDeviceComplianceFeatureToggle) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSharedDeviceComplianceFeatureToggle(val *SharedDeviceComplianceFeatureToggle) *NullableSharedDeviceComplianceFeatureToggle {
	return &NullableSharedDeviceComplianceFeatureToggle{value: val, isSet: true}
}

func (v NullableSharedDeviceComplianceFeatureToggle) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSharedDeviceComplianceFeatureToggle) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


