/*
Jamf Pro API

## Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

API version: production
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the OidcJwksResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OidcJwksResponse{}

// OidcJwksResponse struct for OidcJwksResponse
type OidcJwksResponse struct {
	Keys []OidcJwksResponseKeysInner `json:"keys,omitempty"`
}

// NewOidcJwksResponse instantiates a new OidcJwksResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOidcJwksResponse() *OidcJwksResponse {
	this := OidcJwksResponse{}
	return &this
}

// NewOidcJwksResponseWithDefaults instantiates a new OidcJwksResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOidcJwksResponseWithDefaults() *OidcJwksResponse {
	this := OidcJwksResponse{}
	return &this
}

// GetKeys returns the Keys field value if set, zero value otherwise.
func (o *OidcJwksResponse) GetKeys() []OidcJwksResponseKeysInner {
	if o == nil || IsNil(o.Keys) {
		var ret []OidcJwksResponseKeysInner
		return ret
	}
	return o.Keys
}

// GetKeysOk returns a tuple with the Keys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OidcJwksResponse) GetKeysOk() ([]OidcJwksResponseKeysInner, bool) {
	if o == nil || IsNil(o.Keys) {
		return nil, false
	}
	return o.Keys, true
}

// HasKeys returns a boolean if a field has been set.
func (o *OidcJwksResponse) HasKeys() bool {
	if o != nil && !IsNil(o.Keys) {
		return true
	}

	return false
}

// SetKeys gets a reference to the given []OidcJwksResponseKeysInner and assigns it to the Keys field.
func (o *OidcJwksResponse) SetKeys(v []OidcJwksResponseKeysInner) {
	o.Keys = v
}

func (o OidcJwksResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OidcJwksResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Keys) {
		toSerialize["keys"] = o.Keys
	}
	return toSerialize, nil
}

type NullableOidcJwksResponse struct {
	value *OidcJwksResponse
	isSet bool
}

func (v NullableOidcJwksResponse) Get() *OidcJwksResponse {
	return v.value
}

func (v *NullableOidcJwksResponse) Set(val *OidcJwksResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOidcJwksResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOidcJwksResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOidcJwksResponse(val *OidcJwksResponse) *NullableOidcJwksResponse {
	return &NullableOidcJwksResponse{value: val, isSet: true}
}

func (v NullableOidcJwksResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOidcJwksResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


