/*
Jamf Pro API

## Overview The Jamf Pro API is a RESTful API for Jamf Pro built to enable consistent and efficient programmatic access to Jamf Pro.<br/><br/> The swagger schema can be found [here](/api/schema/). 

API version: production
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"time"
)

// checks if the ApnsPushEnableRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApnsPushEnableRequest{}

// ApnsPushEnableRequest Status information for an enable all clients push request
type ApnsPushEnableRequest struct {
	// Timestamp when the request was created (ISO-8601 format)
	RequestedTime *time.Time `json:"requestedTime,omitempty"`
	// Current status of the request
	Status *string `json:"status,omitempty"`
	// Timestamp when the request was processed (ISO-8601 format), null if not yet processed
	ProcessedTime NullableTime `json:"processedTime,omitempty"`
}

// NewApnsPushEnableRequest instantiates a new ApnsPushEnableRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApnsPushEnableRequest() *ApnsPushEnableRequest {
	this := ApnsPushEnableRequest{}
	return &this
}

// NewApnsPushEnableRequestWithDefaults instantiates a new ApnsPushEnableRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApnsPushEnableRequestWithDefaults() *ApnsPushEnableRequest {
	this := ApnsPushEnableRequest{}
	return &this
}

// GetRequestedTime returns the RequestedTime field value if set, zero value otherwise.
func (o *ApnsPushEnableRequest) GetRequestedTime() time.Time {
	if o == nil || IsNil(o.RequestedTime) {
		var ret time.Time
		return ret
	}
	return *o.RequestedTime
}

// GetRequestedTimeOk returns a tuple with the RequestedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApnsPushEnableRequest) GetRequestedTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.RequestedTime) {
		return nil, false
	}
	return o.RequestedTime, true
}

// HasRequestedTime returns a boolean if a field has been set.
func (o *ApnsPushEnableRequest) HasRequestedTime() bool {
	if o != nil && !IsNil(o.RequestedTime) {
		return true
	}

	return false
}

// SetRequestedTime gets a reference to the given time.Time and assigns it to the RequestedTime field.
func (o *ApnsPushEnableRequest) SetRequestedTime(v time.Time) {
	o.RequestedTime = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApnsPushEnableRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApnsPushEnableRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApnsPushEnableRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ApnsPushEnableRequest) SetStatus(v string) {
	o.Status = &v
}

// GetProcessedTime returns the ProcessedTime field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApnsPushEnableRequest) GetProcessedTime() time.Time {
	if o == nil || IsNil(o.ProcessedTime.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ProcessedTime.Get()
}

// GetProcessedTimeOk returns a tuple with the ProcessedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApnsPushEnableRequest) GetProcessedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProcessedTime.Get(), o.ProcessedTime.IsSet()
}

// HasProcessedTime returns a boolean if a field has been set.
func (o *ApnsPushEnableRequest) HasProcessedTime() bool {
	if o != nil && o.ProcessedTime.IsSet() {
		return true
	}

	return false
}

// SetProcessedTime gets a reference to the given NullableTime and assigns it to the ProcessedTime field.
func (o *ApnsPushEnableRequest) SetProcessedTime(v time.Time) {
	o.ProcessedTime.Set(&v)
}
// SetProcessedTimeNil sets the value for ProcessedTime to be an explicit nil
func (o *ApnsPushEnableRequest) SetProcessedTimeNil() {
	o.ProcessedTime.Set(nil)
}

// UnsetProcessedTime ensures that no value is present for ProcessedTime, not even an explicit nil
func (o *ApnsPushEnableRequest) UnsetProcessedTime() {
	o.ProcessedTime.Unset()
}

func (o ApnsPushEnableRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApnsPushEnableRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestedTime) {
		toSerialize["requestedTime"] = o.RequestedTime
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.ProcessedTime.IsSet() {
		toSerialize["processedTime"] = o.ProcessedTime.Get()
	}
	return toSerialize, nil
}

type NullableApnsPushEnableRequest struct {
	value *ApnsPushEnableRequest
	isSet bool
}

func (v NullableApnsPushEnableRequest) Get() *ApnsPushEnableRequest {
	return v.value
}

func (v *NullableApnsPushEnableRequest) Set(val *ApnsPushEnableRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApnsPushEnableRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApnsPushEnableRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApnsPushEnableRequest(val *ApnsPushEnableRequest) *NullableApnsPushEnableRequest {
	return &NullableApnsPushEnableRequest{value: val, isSet: true}
}

func (v NullableApnsPushEnableRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApnsPushEnableRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


